config/routes.rb
Rails.application.routes.draw do
   devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
 
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy]
  end
  
  devise_for :customers
   root to: "homes#top"
    resources :search, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      collection do
        get :map, :mapshow
        post :map
      end
     end  
    resources :post
    resources :calculate
    resources :customer, only: [:index, :create, :show, :edit, :update] do
      collection do
        get :mypage 
      end
     end
   get "homes/about" => "homes#about", as: "about" 
   get "homes/introduction" => "homes#introduction", as: "introduction" 
   get "homes/completed" => "homes#completed", as: "completed" 
   get "homes/thank" => "homes#thank", as: "thank" 
   get "homes/choice" => "homes#choice", as: "choice"
   get '/Core/Skin/Login.aspx', to: 'login#show'
# 　 get 'search/map_request', to: 'search#map', as: 'map_request'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/calculate.rb
class Calculate < ApplicationRecord
   validates :home_pay, presence: true
  validates :other_payment_amount, presence: true
  validates :rent, presence: true
  validates :security_deposit, presence: true
  validates :key_money, presence: true
  validates :management_fee, presence: true
  validates :guarantee_charge, presence: true
end

app/controllers/calculate_controller.rb
class CalculateController < ApplicationController
  def new
    @calculate = Calculate.new
  end
  
  def index 
  end 
  
  def show
   @calculate = Calculate.find params[:id] 
   @number1 = @calculate["home_pay"] 
   @number2 = @calculate["other_payment_amount"] 
   @number3 = @calculate["rent"] 
   @number4 = @calculate["security_deposit"] 
   @number5 = @calculate["key_money"] 
   @number6 = @calculate["management_fee"] 
   @number7 = @calculate["guarantee_charge"] 
   @hikizan = @number1 - @number2 - @number3 - @number4 - @number5 - @number6 - @number7
  end
  
  def create
    @calculate = Calculate.new(calculate_params)
    if @calculate.save
      flash[:notice] = "計算できました。"
    redirect_to calculate_path(@calculate)
    else
      flash.now[:alert] = "計算に失敗しました。"
      render :new
    end
  end
  
  private
  
   def calculate_params 
    params.require(:calculate).permit(:home_pay, :other_payment_amount, :rent,
    :security_deposit, :key_money, :management_fee, :guarantee_charge) 
   end
end

app/views/calculate/_template.html.erb
<div class="d-flex justify-content-around">
<tbody>
  <tr>
    <th class="col-md-4">
       <%= link_to "Search 様々な地域の家を探そう",search_index_path %>
    </th>
    <th class="col-md-4">
       <%= link_to "Post 情報を投稿し共有しよう", new_post_path %>
    </th>
    <th class="col-md-4">
       <%= link_to "List みんなの投稿を覗いてみよう", post_index_path %>
    </th>
  </tr>
</tbody>
</div>

app/views/calculate/index.html.erb
<div class="text-center border d-inline list-unstyled">
<div class ="top">

　　<h2>Welcome Calculate!</h2>

　　<%= link_to "Calculate", new_calculate_path %>
</div>

<%= render 'calculate/template', calculate: @calculate %>
</div>
<!--https://papael14.com/rails-calculation/-->

app/views/calculate/new.html.erb
<div class="text-center w-auto list-unstyled">
<% if @calculate.errors.any? %>
  <%= @calculate.errors.count %>件のエラーが発生しました
  <ul>
    <% @calculate.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<p>計算数値を入力してください。</p> 
<%= form_with model: @calculate, url: calculate_index_path, method: :post do |f| %>
<div class="text-center border list-unstyled p-4 rounded-0 w-auto">
<h3>ユーザー情報</h3>
<p> 
 <%= f.label :手取り %>
 <%= f.number_field :home_pay %>円
</p>
<p><%= f.label :その他支払額 %>
<%= f.number_field :other_payment_amount %>円
</p>
</div>

<div class="text-center border list-unstyled p-4 rounded-0 w-auto">
<h3>希望賃貸情報</h3>
<p> 
 <%= f.label :賃料 %>
 <%= f.number_field :rent %>円
</p>
<p><%= f.label :敷金 %>
<%= f.number_field :security_deposit %>円
</p>
<p><%= f.label :礼金 %>
<%= f.number_field :key_money %>円
</p>
<p><%= f.label :管理費 %>
<%= f.number_field :management_fee %>円
</p>
<p><%= f.label :保証料 %>
<%= f.number_field :guarantee_charge %>円
</p>
</div>
<p> 
<%= f.submit '完了' %>
</p>
<% end %>

<%= link_to "Topへ", calculate_index_path %>
</div>
<%= render 'calculate/template', calculate: @calculate %>

<!--https://papael14.com/rails-calculation/-->

app/views/calculate/show.html.erb
<div class="text-center border list-unstyled p-4 rounded-0 w-auto">
<p>計算数値を入力してください</p> 
<%= form_with model: @calculate, url: calculate_index_path, method: :post do |f| %>
<h3>ユーザー情報</h3>
<p> 
 <%= f.label :手取り %>
 <%= f.number_field :home_pay %>円
</p>
<p><%= f.label :その他支払額 %>
<%= f.number_field :other_payment_amount %>円
</p>
</div>

<div class="text-center border list-unstyled p-4 rounded-0 w-auto">
<h3>希望賃貸情報</h3>
<p> 
 <%= f.label :賃料 %>
 <%= f.number_field :rent %>円
</p>
<p><%= f.label :敷金 %>
<%= f.number_field :security_deposit %>円
</p>
<p><%= f.label :礼金 %>
<%= f.number_field :key_money %>円
</p>
<p><%= f.label :管理費 %>
<%= f.number_field :management_fee %>円
</p>
<p><%= f.label :保証料 %>
<%= f.number_field :guarantee_charge %>円
</p>
</div>

<div class="text-center border list-unstyled p-4 rounded-0 w-auto">
<p> 
<%= f.submit '完了' %>
</p>
<% end %>
 
 
 <p>結果</p>


 <p>手取り<%= @calculate.home_pay%>円</p></br>
  <p>-その他支払額<%= @calculate.other_payment_amount %>円</p></br>
 <p>-賃料<%= @calculate.rent %>円</p></br>
 <p>-敷金<%= @calculate.security_deposit %>円</p></br>
<p>-礼金<%= @calculate.key_money %>円</p></br>
<p>-管理費<%= @calculate.management_fee %>円</p></br>
<p class="border-bottom">-保証料 <%= @calculate.guarantee_charge %>円</p></br>
 <p>合計=  <%= @hikizan %>円</p>
 
<%= link_to "Topへ", calculate_index_path %>

</div>
<%= render 'calculate/template', calculate: @calculate %>