config/routes.rb
Rails.application.routes.draw do
   devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
 
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy]
  end
  
  devise_for :customers
   root to: "homes#top"
    resources :search, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      collection do
        get :map, :mapshow
        post :map
      end
     end  
    resources :post
    resources :calculate
    resources :customer, only: [:index, :create, :show, :edit, :update] do
      collection do
        get :mypage 
      end
     end
   get "homes/about" => "homes#about", as: "about" 
   get "homes/introduction" => "homes#introduction", as: "introduction" 
   get "homes/completed" => "homes#completed", as: "completed" 
   get "homes/thank" => "homes#thank", as: "thank" 
   get "homes/choice" => "homes#choice", as: "choice"
   get '/Core/Skin/Login.aspx', to: 'login#show'
# 　 get 'search/map_request', to: 'search#map', as: 'map_request'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
  def about
    
  end
  def introduction
    
  end
  def completed
    
  end
  
  def thank
    
  end
  
end

app/views/homes/about.html.erb
<div class="text-center border d-inline list-unstyled">
<h2>About</h2>
<h2>Taku Homeとは</h2>
<h2>どんな場所にいても自分が住みたい場所を熟知でき</br>

安心して生活できるよう自身の収入から</br>

生活費の内訳を差し引きし計算できる</br>

賃貸コミュニティサイトです!</h2>
</div>

app/views/homes/choice.html.erb
<div class="text-center border d-inline list-unstyled">
 <h4>選択してください。</h4>
 <h5>
  <%= link_to "Create 物件の登録をしよう", new_search_path %>
 </h5>

 <h5>
  <%= link_to "Search 様々な地域の家を探そう", search_index_path %>
 </h5>
</div>

<div class="d-flex justify-content-around">
 <tbody>
    <tr>
      <td>
        <%= link_to "Post 情報を投稿し共有しよう", new_post_path %>
      </td>
      <td>
         <%= link_to "List みんなの投稿を覗いてみよう", post_index_path %>
      </td>
      <td>
         <%= link_to "Calculate 様々な内訳を計算しよう", calculate_index_path %>
      </td>
    </tr>
 </tbody>
 </div>

app/views/homes/completed.html.erb
<div class="text-center border d-inline list-unstyled">
<h1>completed!!</h1>
      <h4>
        <%= link_to "Search", choice_path %>
      </h4>
      <h4>
        <%= link_to "Post", new_post_path %>
      </h4>
      <h4>
        <%= link_to "List", post_index_path %>
      </h4>
      <h4>
        <%= link_to "Calculate", calculate_index_path  %>
      </h4>
</div>

app/views/homes/introduction.html.erb
<div class="text-center border d-flex list-unstyled">
<div class="text-center border list-unstyled">
<h2>Introduction</h2>
  <h3><%= image_tag 'IMG_9807.jpg', size: "400x400" %></h3>
<h3>Takumi（1993年生まれ)</h3>
</div>
<div class="border list-unstyled">
  <h4></h4></br>
   <h4></h4>
<h4>工業大学にて機械工学を学びダイヤモンド研磨の研究に励みました💍</br>
</br>
その後、ものづくりに興味を持ち建設業の仕事に就職しました🏢</br>
</br>
その当時に、仕事で様々なホームページを閲覧する時や</br>
プライベートでもアプリやサイトを使用する時に
</h4>
<h2>
「私にもこういうサイトやホームページを作ってみたい！」
</h2>
<h4>
という熱い思いを覚え、それを叶えるため現在プログラミングを学習中💻</br>
</br>
誰よりも負けず嫌いで途中で投げ出すことが嫌いな為</br>
何事にも全力で取り組む姿勢は誰にも負けません🔥🔥</br>
</br></h4>
<h1>今サイトをどうぞ宜しく御願いします🌊</h1>
</div>
</div>

app/views/homes/thank.html.erb
<div class="text-center border d-inline list-unstyled">
<h4>Log out Successfull!</br>
Thank you for using this site！!</h4>
<li>
　<%= link_to "Home", root_path %>
</li>
</div>

app/views/homes/top.html.erb
<div class="text-center border d-inline list-unstyled">
<h1>Home</h1>
  <h2><%= image_tag 'IMG_9840.png', size: "400x400" %></h2>
<h3>
<%= link_to "Log in", new_customer_session_path %>
</h3>
 <h3>
<%= link_to "Sign up", new_customer_registration_path %>
</h3>
</div>