config/routes.rb
Rails.application.routes.draw do
   devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
 
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy]
  end
  
  devise_for :customers
   root to: "homes#top"
    resources :search, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      collection do
        get :map, :mapshow
        post :map
      end
     end  
    resources :post
    resources :calculate
    resources :customer, only: [:index, :create, :show, :edit, :update] do
      collection do
        get :mypage 
      end
     end
   get "homes/about" => "homes#about", as: "about" 
   get "homes/introduction" => "homes#introduction", as: "introduction" 
   get "homes/completed" => "homes#completed", as: "completed" 
   get "homes/thank" => "homes#thank", as: "thank" 
   get "homes/choice" => "homes#choice", as: "choice"
   get '/Core/Skin/Login.aspx', to: 'login#show'
# 　 get 'search/map_request', to: 'search#map', as: 'map_request'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # before_commit :is_matching_login_user, only: [:edit, :update, :destroy]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :searches, dependent: :destroy
        has_many :posts, dependent: :destroy
        has_one_attached :image
        validates :name, presence: true
        validates :email, presence: true
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def mypage
    @customer = current_customer
  end

  def edit
    @customer = Customer.find(current_customer.id)
  end

  def update
    if @customer.update(customer_params)
    flash[:notice] = "You have updated costomer successfully."
    redirect_to  mypage_customer_index_path
    else
    render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :address, :comment, :evaluation, :customer_id, :star,:image)
  end

  def is_matching_login_user
    @customer = Customer.find(params[:id])
    unless @customer.id == current_customer.id
     redirect_to request.referer
    end
  end
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customer/_template.html.erb
<div class="d-flex justify-content-around">
<tbody>
  <tr>
    <td>
       <%= link_to "Search 様々な地域の家を探そう",search_index_path %>
    </td>
    <td>
       <%= link_to "Post 情報を投稿し共有しよう", new_post_path %>
    </td>
    <td>
       <%= link_to "List みんなの投稿を覗いてみよう", post_index_path %>
    </td>
    <td>
       <%= link_to "Calculate 様々な内訳を計算しよう", calculate_index_path  %>
    </td>
  </tr>
</tbody>

app/views/customer/edit.html.erb
<div class="text-center border d-inline list-unstyled">
<h4>Edit</h4>
<%= form_with model: @customer do |f| %>
  <label for ="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前" %>
  </br>
  <label for = "inputEmail">Email</label>
    <%= f.email_field :email, autofocus: true, id:"inputEmail", placeholder:"email" %>
  </br>
  <label for = "inputPasswaord">Password</label>
    <%= f.text_field :password, autofocus: true, id:"inputPassword", placeholder:"password" %>
    </br>
 <label for = "inputImage">Image</label>
    <%= f.file_field :image, autofocus: true, id:"inputImage", placeholder:"Image" %>
     </br>
  <%= f.submit '完了' %>
<% end %>
<%= render 'customer/template', customer: @customer %>

</div>

app/views/customer/index.html.erb
 <div>
       <%= current_customer.name%>
      </div>
<%= link_to "編集", edit_customer_path(@customers) %>
<% @customers.each do |customer| %>
 <% if customer.image.attached? %>
  <%= image_tag customer.image, size: "200x200" %>
  <% else %>
    <%= image_tag 'no_image', size: "200x200" %>
  <% end %>
  <h4>No</h4>
<%= link_to current_customer.id, customer_path(current_customer.id)  %> 
<h4>都道府県</h4>
<%= customer.address %>
<h4>コメント</h4>
<%= customer.comment %>
<h4>評価</h4>
  <div id="star_<%= customer.id %>"></div>
  
<script>
  let elem = document.querySelector('#star_<%= customer.id %>');
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= customer.star %>",
    readOnly: true,　　
  };
  raty(elem, opt);

</script>

<%= link_to "編集", edit_post_path(customer.id) %>
<%= link_to "削除", post_path(customer.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
<% end %>

<%= render 'customer/template', customer: @customer %>

app/views/customer/mypage.html.erb
<div class="text-center border d-flex　justify-content-around list-unstyled p-3 rounded-0">
 <h4><%= @customer.name %>
 <% if @customer.id == current_customer.id %>
<%= link_to "編集", edit_customer_path(@customer) %>
<% end %>
</h4>
  <% if @customer.image.attached? %>
  <%= image_tag @customer.image, size: "200x200" %>
  <% else %>
    <%= image_tag 'no_image', size: "200x200" %>
  <% end %>
</div>
<table class="table text-left">
  <thead>
    <tr>
      <th class="col-md-3">都道府県</th>
      <th class="col-md-3">コメント</th>
      <th colspan="col-md-3">評価</th>
      <th class="col-md-3"></th>
    </tr>
  </thead>

<tbody>
 <% @customer.posts.each do |post| %>
  <tr>
    <td class="col-md-3 text-left"><%= post.address %></td>
    <td class="col-md-3 text-left"><%= post.comment %></td>
    <td class="col-md-3 text-left"><div id="star_<%= post.id %>"></div>
    <script>{
  let elem = document.querySelector('#star_<%= post.id %>');
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= post.star %>",
    readOnly: true,　　
  };
  raty(elem, opt);
}
</script>
  </td>
    <td class="col text-center" style="width: 50px;">
      <% if @customer.id == current_customer.id %>
      <%= link_to "編集", edit_post_path(post.id) %>
    <%= link_to "削除", post_path(post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
      <% end %>
    </td>
  </tr>
</tbody>

<% end %>

<%= render 'customer/template', customer: @customer %>

app/views/customer/show.html.erb
<div class="text-center border d-flex　justify-content-around list-unstyled p-3 rounded-0">
  <h4><%= @customer.name %>
   <% if @customer.id == current_customer.id %>
<%= link_to "編集", edit_customer_path(@customer) %>
<% end %>
</h4>
  <% if @customer.image.attached? %>
  <%= image_tag @customer.image, size: "200x200" %>
  <% else %>
    <%= image_tag 'no_image', size: "200x200" %>
  <% end %>
</div>
<table class="table text-center">
  <thead>
    <tr>
      <th class="col-md-2">都道府県</th>
      <th class="col-md-2">コメント</th>
      <th colspan="col-md-3">評価</th>
      <th style="width: 50px;"></th>
    </tr>
  </thead>

<tbody>
 <% @customer.posts.each do |post| %>
  <tr>
    <td class="col-md-3 text-center"><%= post.address %></td>
    <td class="col-md-3 text-center"><%= post.comment %></td>
    <td class="col-md-3 text-center"><div id="star_<%= post.id %>"></div>
    <script>{
  let elem = document.querySelector('#star_<%= post.id %>');
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= post.star %>",
    readOnly: true,　　
  };
  raty(elem, opt);
}
</script>
  </td>
    <td class="col text-center" style="width: 50px;">
      <% if @customer.id == current_customer.id %>
      <%= link_to "編集", edit_post_path(post.id) %>
    <%= link_to "削除", post_path(post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
      <% end %>
    </td>
  </tr>
</tbody>

<% end %>

<%= render 'customer/template', customer: @customer %>