config/routes.rb
Rails.application.routes.draw do
   devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }
 
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy]
  end
  
  devise_for :customers
   root to: "homes#top"
    resources :search, only: [:new, :index, :show, :create, :edit, :update, :destroy] do
      collection do
        get :map, :mapshow
        post :map
      end
     end  
    resources :post
    resources :calculate
    resources :customer, only: [:index, :create, :show, :edit, :update] do
      collection do
        get :mypage 
      end
     end
   get "homes/about" => "homes#about", as: "about" 
   get "homes/introduction" => "homes#introduction", as: "introduction" 
   get "homes/completed" => "homes#completed", as: "completed" 
   get "homes/thank" => "homes#thank", as: "thank" 
   get "homes/choice" => "homes#choice", as: "choice"
   get '/Core/Skin/Login.aspx', to: 'login#show'
# 　 get 'search/map_request', to: 'search#map', as: 'map_request'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Meshiterro</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <% if admin_signed_in? %>
    <div class="text-right">
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %>
    </div>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>TakuHome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=hoge">
    <%#= include_gon %>
    <!--<script type="text/javascript" src="//jpostal-1006.appspot.com/jquery.jpostal.js"></script>-->
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <header>
        <div class="p-3 d-flex justify-content-between shadow-lg ">
        <div class="h-25 rounded border border-3 text-center align-middle" style="width: 150px;" >
        <h1>Taku</br>Home</h1>
        </div>
    <% if customer_signed_in? %>
       <div>User:
       <%= link_to current_customer.name, mypage_customer_index_path %>
      </div>
    <ul class="p-2 list-unstyled">
     <li>
        <%= link_to "Search", choice_path %>
      </li>
      <li>
        <%= link_to "Post", new_post_path %>
      </li>
      <li>
        <%= link_to "List", post_index_path %>
      </li>
      <li>
        <%= link_to "Calculate", calculate_index_path %>
      </li>
      <li>
        <%= link_to "Log out", destroy_customer_session_path, method: :delete %>
      </li>
     </ul>
    </div>
    <% else %>
    <div>
     <ul class="p-2 list-unstyled">
     <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <%= link_to "About", about_path %>
      </li>
      <li>
        <%= link_to "Introduction", introduction_path %>
      </li>
      <li>
        <%= link_to "Sign up", new_customer_registration_path %>
      </li>
      <li>
        <%= link_to "Log in", new_customer_session_path %>
      </li>
      </ul>
    </div>
    </div>
    <% end %>
  </header>
  <main>
   <% flash.each do |message_type, message| %>
      <div class="flash-message <%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    </main>
  </body>
</html>